workflows:
  hidden_santa_release:
    name: Hidden Santa Release Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          flutter gen-l10n
      - name: Build iOS .app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/app/outputs/flutter-apk/app-release.apk
