workflows:
  hidden_santa_release:
    name: Hidden Santa iOS Simulator Build
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
          flutter gen-l10n
      - name: Build iOS for simulator
        script: |
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - build/app/outputs/flutter-apk/app-release.apk
