// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97Slbu6HCogc8QLQa8uw3xUKqS3uJQss',
    appId: '1:856617478135:web:c885ac6cdf4142987f70f2',
    messagingSenderId: '856617478135',
    projectId: 'hidden-santa-220ff',
    authDomain: 'hidden-santa-220ff.firebaseapp.com',
    storageBucket: 'hidden-santa-220ff.firebasestorage.app',
    measurementId: 'G-4ZH8R1JMHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkN-fFLtwWiHaAZqx3rhjLt8u0hvAGvMQ',
    appId: '1:856617478135:android:bb07321fa4ba6dc17f70f2',
    messagingSenderId: '856617478135',
    projectId: 'hidden-santa-220ff',
    storageBucket: 'hidden-santa-220ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs_3_lZT7Ny39ZYIgyPbV1Ko3Rgp8cm0M',
    appId: '1:856617478135:ios:c71d3555a0fc4f287f70f2',
    messagingSenderId: '856617478135',
    projectId: 'hidden-santa-220ff',
    storageBucket: 'hidden-santa-220ff.firebasestorage.app',
    iosBundleId: 'com.example.hiddenSanta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs_3_lZT7Ny39ZYIgyPbV1Ko3Rgp8cm0M',
    appId: '1:856617478135:ios:c71d3555a0fc4f287f70f2',
    messagingSenderId: '856617478135',
    projectId: 'hidden-santa-220ff',
    storageBucket: 'hidden-santa-220ff.firebasestorage.app',
    iosBundleId: 'com.example.hiddenSanta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB97Slbu6HCogc8QLQa8uw3xUKqS3uJQss',
    appId: '1:856617478135:web:a751a5d62dc3284f7f70f2',
    messagingSenderId: '856617478135',
    projectId: 'hidden-santa-220ff',
    authDomain: 'hidden-santa-220ff.firebaseapp.com',
    storageBucket: 'hidden-santa-220ff.firebasestorage.app',
    measurementId: 'G-F5G15W5DV5',
  );
}
